name: Tech Association of the Bluegrass
url: https://www.tabky.org
description: "TAB exists to support and promote software technology among area students and professionals through events, education, and advocacy."
author: Awesome Inc
google_verification: 
highlighter: rouge
permalink: /blog/:title/
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
exclude: [node_modules]
# Useful info, update here for sitewide usage